
# This will verbose debug messages to the console
# when toggled on.
debug: false

# This option is used by MMOInventory and MMOCore to synchronize
# player data between proxy-connected servers. When a player changes
# server, the plugin tries to fetch new data X times every 1s, up
# to a maximum of 5 times by default.
#
# Use a higher value if your SQL connection is weak to avoid
# player data loss.
max-sync-tries: 5
